// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace proceso_etl.Configurations;

[Table("Category", Schema = "dim")]
[Index("Name", Name = "UQ__Category__737584F644E0A45D", IsUnique = true)]
public partial class Category
{
    [Key]
    public int CategoryId { get; set; }

    [Required]
    [StringLength(40)]
    [Unicode(false)]
    public string Name { get; set; }
}