// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace proceso_etl.Configurations;

[Table("City", Schema = "dim")]
[Index("CountryId", Name = "IX_City_Country")]
public partial class City
{
    [Key]
    public int CityId { get; set; }

    [Required]
    [StringLength(100)]
    [Unicode(false)]
    public string CityName { get; set; }

    public int CountryId { get; set; }
}