// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace proceso_etl.Configurations;

[Table("Country", Schema = "dim")]
[Index("CountryName", Name = "UQ__Country__E056F201E501DEC6", IsUnique = true)]
public partial class Country
{
    [Key]
    public int CountryId { get; set; }

    [Required]
    [StringLength(100)]
    [Unicode(false)]
    public string CountryName { get; set; }
}