// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace proceso_etl.Configurations;

[Table("Customer", Schema = "dim")]
[Index("CityId", Name = "IX_Customer_City")]
[Index("Email", Name = "IX_Customer_Email")]
[Index("Email", Name = "UQ__Customer__A9D105341ED6017E", IsUnique = true)]
public partial class Customer
{
    [Key]
    public int CustomerId { get; set; }

    [Required]
    [StringLength(50)]
    [Unicode(false)]
    public string FirstName { get; set; }

    [Required]
    [StringLength(50)]
    [Unicode(false)]
    public string LastName { get; set; }

    [Required]
    [StringLength(100)]
    [Unicode(false)]
    public string Email { get; set; }

    public int CityId { get; set; }
}