// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace proceso_etl.Configurations;

[Table("OrderStatus", Schema = "dim")]
[Index("Name", Name = "UQ__OrderSta__737584F6FFCAF05C", IsUnique = true)]
public partial class OrderStatus
{
    [Key]
    public int StatusId { get; set; }

    [Required]
    [StringLength(15)]
    [Unicode(false)]
    public string Name { get; set; }
}