// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace proceso_etl.Configurations;

[Table("Phone", Schema = "dim")]
public partial class Phone
{
    [Key]
    public int PhoneId { get; set; }

    public int CustomerId { get; set; }

    [Required]
    [StringLength(30)]
    [Unicode(false)]
    public string PhoneNumber { get; set; }
}