// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace proceso_etl.Configurations;

[Table("Product", Schema = "dim")]
[Index("CategoryId", Name = "IX_Product_Category")]
public partial class Product
{
    [Key]
    public int ProductId { get; set; }

    [Required]
    [StringLength(40)]
    [Unicode(false)]
    public string ProductName { get; set; }

    public int CategoryId { get; set; }

    [Column(TypeName = "decimal(10, 2)")]
    public decimal Price { get; set; }

    public int Stock { get; set; }
}