// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace proceso_etl.Configurations;

[Table("Orders", Schema = "fact")]
[Index("CustomerId", Name = "IX_Orders_Customer")]
[Index("CustomerId", "OrderDate", Name = "IX_Orders_Customer_Date")]
[Index("OrderDate", "StatusId", Name = "IX_Orders_Date_Status")]
[Index("StatusId", Name = "IX_Orders_Status")]
[Index("OrderYear", "OrderMonth", Name = "IX_Orders_Year_Month")]
public partial class Order
{
    [Key]
    public int OrderId { get; set; }

    public int CustomerId { get; set; }

    public int StatusId { get; set; }

    public DateTime OrderDate { get; set; }

    public int? OrderYear { get; set; }

    public int? OrderMonth { get; set; }
}