// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using proceso_etl.Configurations;
using proceso_etl.Models;
using System;
using System.Collections.Generic;

namespace proceso_etl.Models.Configurations
{
    public partial class OrderConfiguration : IEntityTypeConfiguration<Order>
    {
        public void Configure(EntityTypeBuilder<Order> entity)
        {
            entity.HasKey(e => e.OrderId).HasName("PK__Orders__C3905BCFC116D668");

            entity.Property(e => e.OrderMonth).HasComputedColumnSql("(datepart(month,[OrderDate]))", true);
            entity.Property(e => e.OrderYear).HasComputedColumnSql("(datepart(year,[OrderDate]))", true);

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<Order> entity);
    }
}
