// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using proceso_etl.Configurations;
using proceso_etl.Models;
using System;
using System.Collections.Generic;

namespace proceso_etl.Models.Configurations
{
    public partial class OrderStatusConfiguration : IEntityTypeConfiguration<OrderStatus>
    {
        public void Configure(EntityTypeBuilder<OrderStatus> entity)
        {
            entity.HasKey(e => e.StatusId).HasName("PK__OrderSta__C8EE2063C345663D");

            entity.Property(e => e.StatusId).ValueGeneratedOnAdd();

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<OrderStatus> entity);
    }
}
